{% set name = "openmotif" %}
{% set version = "2.3.8" %}
{% set sha256 = "859b723666eeac7df018209d66045c9853b50b4218cecadb794e2359619ebce7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://downloads.sourceforge.net/project/motif/Motif%20{{ version }}%20Source%20Code/motif-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0003_fix_ftbfs_binutils-gold.patch  # [linux]

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - make
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - flex
    - freetype
    - fontconfig
    - libpng
    - jpeg
    - xorg-libxt
    - xorg-libxext
    - xorg-libxft
    - xorg-xbitmaps
    - xorg-libxp
    - xorg-libxmu
    - xorg-makedepend
    - libiconv

  run:
    - freetype
    - fontconfig
    - libpng
    - jpeg
    - xorg-libxt
    - xorg-libxext
    - xorg-libxft
    - xorg-libxp
    - xorg-libxmu
    - libiconv

test:
  commands:
    - 'test "`uil 2>&1| tr -d ''\n''`" = "Severe: no source file specified"'
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

outputs:
  - name: openmotif-dev
    script: install_dev.sh
    build:
      run_exports:
        # clients need `openmotif` when using `openmotif-dev`
        # ABI compatability looks rather unchanging:
        # https://abi-laboratory.pro/index.php?view=timeline&l=motif
        - {{ pin_subpackage('openmotif') }}
    requirements:
      # `openmotiv-dev` headers are exactly for same version
      - {{ pin_subpackage('openmotif', exact=True) }}
  - name: openmotif
    script: install_main.sh
  - name: openmotif-doc
    script: install_doc.sh
    requirements:
      - {{ pin_subpackage('openmotif', exact=True) }}

about:
  home: http://motif.ics.com
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYING
  summary: 'Motif user interface component toolkit.'

extra:
  recipe-maintainers:
    - epruesse
